### ISSUE TITLE
Robot not responsive - cannot connect

### ISSUE THREAD

**Issue by MarcSallent** [AmberInside/Amber_AI_ROS2#1]
Hello,

I got the robot to work around three days ago. I just tested that it was working correctly and shut it down. I was working with the first firmware that was published in this page.
Two days ago I installed the new firmware published and I couldn't get it to work. I thought that it was the firmware but reinstalling the old one didn't work either.
Upon inspection, I found the following in firefox:
- I connect to 127.0.0.1:85. The page loads
- I try to connect hitting the button "Connection status: disconnected"
- I get an empty error message
- Looking at the console, I see that it makes a POST call to `/api/v1/initialize-b1/` and I get this response:
`{"code": 200, "message": "初始化成坊", "data": {"realtime_data": [-2, 0, 0, 1, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, 0.0]}}`

I have tried repositioning the robot, changing the order of hitting the buttons, different power on sequences, both firmwares...

Thanks

**Comment by MarcSallent** [comment]
Also: executing `b1_demo/b1` I get this output:
[RT SPI] Open

Failed to setschedparam: Operation not permitted

[PeriodicTask] Start spi (0 s, 4999999 ns)

ffffffff~~~~~~~~~ ffffffff ~~~~~~~~~~~ 0 ~~~~~~~~~~~~~ 0.303027

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

ffffffff~~~~~~~~~ ffffffff ~~~~~~~~~~~ 0 ~~~~~~~~~~~~~ 0.999980

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

ffffffff~~~~~~~~~ ffffffff ~~~~~~~~~~~ 0 ~~~~~~~~~~~~~ 0.315065

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

ffffffff~~~~~~~~~ ffffffff ~~~~~~~~~~~ 0 ~~~~~~~~~~~~~ -0.805237

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff

-nan~~~~~~~~~-nan~~~~~~~~~~~~~-nan~~~~~~~~~~~~~~~~ffff...`

**Comment by AmberInside** [comment]
Thanks for your post, power off  Ubuntu, plug out and in the power cable, restart and try it again.

**Comment by AmberInside** [comment]
BTW,  if you want to try AMBER Robotic Studio by http://127.0.0.1:85 or trying the b1_demo , make sure to keep B1  to Zero Position, connect all the cables and power on the Master Box  first.  See the the exact process  by visiting https://github.com/AmberInside/Amber_AI_ROS2/wiki/Launch-AMBER-Studio,-web-based-controller-for-AMBER-B1

**Comment by MarcSallent** [comment]
> Thanks for your post, power off the Master Box, restart and try it again.

... It worked O_O
If I turn everything on at the same time (plugging a power strip), it never connects to the robot.
It works if I power everything up except the control box, wait a few seconds, and then I power the control box. 

Thanks
