### ISSUE TITLE
Missing a file from the boot USB drive

### ISSUE THREAD

**Issue by awtu2** [AmberInside/Amber_AI_ROS2#11]
I have the early backer USB drive and following the instruction from the Amber B1 quick start guide. I follow the steps to step 5.2 of the guide when I am supposed to partition /dev/mmcblk0p2 that needs to be mounted. That file isn't on the USB drive. I down loaded my own bootable USB from Github and followed the guide and that file again isn't showing as per the instruction. 

This what I see...

![screen shot](https://user-images.githubusercontent.com/34406349/157148367-27a39bd3-ea12-490a-8127-2908612a5971.jpg)

**Comment by AmberInside** [comment]
The picture you post seems it's the usb drive you made on your own. 

1, You mean you have made a new usb drive installer on you own by the link  below? And it doesn't work still? 

2, Please make sure you format the usb drive first following the step 1 by the Ventoy.

https://github.com/AmberInside/Amber_AI_ROS2/wiki/AMBER-B1-Wiki-&-How#how-to-make-a-bootable-usb-installer-on-your-own

**Comment by awtu2** [comment]
Thanks for replying,
First I used the USB drive sent by Amber, I followed the guide to step 5.2 and it was the same as the picture I loaded. So I figured the USB drive they sent must have been corrupted. So I used my own USB Drive to create my own bootable USB. I followed the steps from the guide, downloaded and used Ventoy, then copied AMBER_ROS2.ISO file to the drive and it's the same as the picture I loaded. Its missing the  /dev/mmcblk0p2....... is the guide missing a step? I tried a different USB stick and on a different computer got the same results.

Download Link: https://www.ventoy.net/en/download.html

Make bootable USB drive: https://www.ventoy.net/en/doc_start.html

Step 2, Download AMBER_ROS2.ISO from the link below.

https://drive.google.com/file/d/1-08f86JbY6Kv-1gVg-EzsEG9GFaFyXK1

Step 3, Copy AMBER_ROS2.ISO to the USB Drive made by Step 1.

**Comment by AmberInside** [comment]
It seems wired.  We made lots of USB by those steps. 

The size of /dev/mmcblk0p1  in the picture you post is not correct, generally it should be around 500MB.  Could you format it with Ventoy and try again.     

By the way, which version of Windows  is in your computer?

**Comment by MarcSallent** [comment]
I had the same issue. Somewhere in this Twitter thread I wrote the solution 

https://twitter.com/marcsallent/status/1491177822282723330

**Comment by awtu2** [comment]
Hi MarcSallent,

I read your twitter thread and I didn't understand what you did. You stated you had to "delete mmcblk0 and recreate them all in the same screen" I didn't understand that. Could you break it down by step? 

Hi AmberInside,

I am using Windows 10. The USB sent to me has the exact same setup as the one I downloaded following the guide Step 5.2 isnt the same as the guide. Which is why I thought the guide was wrong. I have tired countless times using Vintoy the guide and just guessing and I come to the same screen at the end /dev/mmcblk0p2 isn't there. I've used different web browsers to download the ROS2.ISO and different USB sticks.

**Comment by awtu2** [comment]
To AmberInside,

this is a screen shot of the USB sent to me as an early backer. you can see from the factory its the same as the one USB's  i've been trying to download to create my own bootable USB 

![20220308_081051](https://user-images.githubusercontent.com/34406349/157279098-2908f136-bffe-4bdf-a23c-77be8fe77a33.jpg)
drive.

**Comment by AmberInside** [comment]
> I had the same issue. Somewhere in this Twitter thread I wrote the solution https://twitter.com/marcsallent/status/1491177822282723330
> […](#)
> On 8 Mar 2022, at 10:56, AMBER Robotics ***@***.***> wrote: ﻿ It seems wired. We made lots of USB by those steps. We'll try again and text u later. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

**Comment by AmberInside** [comment]
Just like what Marc Sallent mention , the following link show how to fix this issue.

[https://docs.google.com/document/d/1aeMmQKioEe3Ji4QClzYlpGu5YMxJ7QPqT-3Z4ZH5u80/](url)

**Comment by awtu2** [comment]
Hi AmberInsider, 

I have tried AMBER_ROS2 Bootable Firmware Installation instructions several times and I always end at the same point Step 5.2. I checked Marc Sallent twitter feed where he mentioned he had the same problem but he doesn't say how he fixed it. just that he had the same problem. I have reached out to him for help and I haven't heard back from him.

**Comment by awtu2** [comment]
This is what your installation instruction say my USB drive should look like at step 5.2
![20220309_064140](https://user-images.githubusercontent.com/34406349/157465538-f34474a3-a1ce-47ea-9bd0-4a4a5a7e1d1a.jpg)

**Comment by awtu2** [comment]
This is what your USB drive sent to me as an early backer looks like at step 5.2


![screen shot](https://user-images.githubusercontent.com/34406349/157465742-27293258-7fe3-4631-a56b-2b455de7dc97.jpg)

**Comment by awtu2** [comment]
I cant move to the next step in the AMBER_ROS2 Bootable Firmware Installation guide.

**Comment by MarcSallent** [comment]
Taking care of the baby these days, not much time to review it. This should put you in the right path:

> My System Install screen didn't match the one in the [docs shared by amber](https://docs.google.com/document/d/1MU08JQNKIl4DXH71kOS0MwCSJQCvQ1__gY2SRo5ZNiA/edit) - mmcblk0p1 and mmcblk0p2 didn't exist.

> I went ahead and deleted mmcblk0. Then, at the right bar, the screen presented me the options to recreate the partitions. I did it just copying the settings shown in the amber docs

https://www.reddit.com/r/amber_robot/comments/sntnng/first_issue_solved_had_to_recreate_partitions/

**Comment by awtu2** [comment]
Sorry to pull you away from your family, I do apricate your help. ok when I get to the file screen this what I see.

![20220309_125100](https://user-images.githubusercontent.com/34406349/157534382-aa592727-0897-4e19-b92c-27c0d53342ac.jpg)

**Comment by awtu2** [comment]
I then delete /dev/mmcblk0 then I get this screen.

![20220309_125651](https://user-images.githubusercontent.com/34406349/157534908-62466f58-52dc-4a3d-845e-80fcc908f973.jpg)

**Comment by awtu2** [comment]
I still don't get the mmcblk0p2. I created my own USB bootable following there amber instructions using Ventoy and coping the amber ROS2.ISO to the thumb drive and I get the same results. I am using Win10, I used to different laptops computers, I used different internet bowers (google and firefox) to download the .ISO file, I switched to a new thumb drive and I arrive at the same results.

**Comment by nambogit** [comment]
It looks like you have to recreate the partitions - they sent you better instructions but you might not have looked at them since the linking was messed up. Try this link -

https://docs.google.com/document/d/1aeMmQKioEe3Ji4QClzYlpGu5YMxJ7QPqT-3Z4ZH5u80/

**Comment by awtu2** [comment]
WOWWW, I never saw these instructions!!!! That's my issue. The Amber links giving never took me there!! Thank you Sir. I just saw the /dev/mmcblk0p2. 

It took me three weeks to get to this point. Fingers crossed!! 

![20220309_133813_HDR](https://user-images.githubusercontent.com/34406349/157540786-ea893ae2-c574-46da-9429-76741d9f5ba4.jpg)
