### ISSUE TITLE
Running the first script on the Terminal

### ISSUE THREAD

**Issue by awtu2** [AmberInside/Amber_AI_ROS2#12]
I loaded up the software from the bootable USB and rebooted the computer and everything looks good so far. I zero the arm release the e-stop plug in the power supply for the arm then I powered on the computer and open the terminal and ran /home/amber/ros2_ws/start.sh It looks like the script failed. Is that normal cause after the I ran the second script I wasn't able to connect to the arm.

![20220309_141720_HDR](https://user-images.githubusercontent.com/34406349/157549296-6a96a7dc-4346-40e2-9566-5a18234e9dac.jpg)

**Comment by AmberInside** [comment]
Try /home/amber/ros2_start.sh

**Comment by awtu2** [comment]
I ran it and the reply was "No such file or directory"

**Comment by MrAsana** [comment]
the sh name is ros2_start.sh,   not start.sh

**Comment by AmberInside** [comment]
Tha sh name is  ros2_starat.sh, not start.sh;  
If there is no any script file in ros2_ws directory,  make a new file of start.sh,  the code is as the following.

Step 1, 
```
#!/bin/bash
cd  /home/amber/ros2_ws
source  install/setup.bash
nohup ros2 launch amber_b1_bringup amber_b1_hw_gui.launch.py  >/home/amber/ros2_ws/ros.out 2>&1 &
```

Step 2,
The last thing need to do is add execute permission  to start.sh file. 
`chmod  o+x  start.sh`

And try to run   /home/amber/ros2_ws/start.sh

**Comment by awtu2** [comment]
Ok where do I input this too. I see a ros2_ws folder 

![20220310_191426~2](https://user-images.githubusercontent.com/34406349/157795363-d19572b3-75f7-4ca5-92e6-d64a04497c2c.jpg)

**Comment by nambogit** [comment]
I’m not sure what you’re asking, but it looks like the command should be:

/home/amber/ros2_ws/ros2_start.sh

After that try:

/home/amber/b1.sh

If it’s not finding files you should check your directories in case they’re named something slightly different. Hope that helps!

**Comment by awtu2** [comment]
Thank you very much!!!! My status is now showing as connected!!!

**Comment by nambogit** [comment]
No problem! The discord is also a great resource if you have questions other users can answer -

https://discord.gg/GRKUWb5B

**Comment by majdros** [comment]
On my Amber B1 Master Box, the directories `amber_robot_studio_backend` and `ros2_ws` are missing.

I have updated `/home/amber/b1.sh`, `/home/amber/initCAN.sh`, and `/home/amber/amber_core/initCAN.sh`.

Running `./b1.sh` produces:

```
./b1.sh: line 49: /home/amber/ros2_ws/ros.out: No such file or directory
grep: /home/amber/ros2_ws/ros.out: No such file or directory
```

And `cat p.out` shows:

```
python3: can't open file '/home/amber/amber_robot_studio_backend/manage.py': [Errno 2] No such file or directory
```



---------------------------------------------------------
root@amber-master:~# ls
amber_api   b1.sh      initCAN.sh  nohup.out         p.out     test.py      watchTemp.sh
amber_core  dashboard  Install     position_mode.py  sin_wave  watchlog.sh  zero.py

root@amber-master:~# ls -la
total 144
drwxr-x--- 13 amber amber  4096 Nov 26 15:38 .
drwxr-xr-x  3 root  root   4096 Dec  6  2023 ..
drwxrwxr-x  3 amber amber  4096 Nov 10 12:44 amber_api
drwxrwxr-x  4 amber amber  4096 Dec  9  2024 amber_core
-rwxr-xr-x  1 root  root   4506 Nov 18 16:54 b1.sh
-rw-------  1 amber amber 23665 Nov 26 14:56 .bash_history
-rw-r--r--  1 amber amber   220 Jan  6  2022 .bash_logout
-rw-r--r--  1 amber amber  3939 Dec  6  2023 .bashrc
drwx------  3 amber amber  4096 Dec  7  2023 .cache
drwxr-xr-x  3 root  root   4096 Dec  6  2023 .cmake
drwx------  3 amber amber  4096 Dec  6  2023 .config
drwxrwxr-x  8 amber amber  4096 Nov 10 14:41 dashboard
-rwxrwxr-x  1 amber amber   174 Jun 13  2024 initCAN.sh
drwxrwxr-x  4 amber amber  4096 Nov 10 12:02 Install
-rw-------  1 amber amber    20 Nov 26 15:04 .lesshst
drwxrwxr-x  7 amber amber  4096 Jun 14  2024 .local
-rw-------  1 amber amber   606 Dec  9  2024 nohup.out
-rw-rw-r--  1 amber amber   164 Aug 19  2024 position_mode.py
-rw-r--r--  1 root  root    113 Nov 26 15:39 p.out
-rw-r--r--  1 amber amber   807 Jan  6  2022 .profile
drwxrwxr-x  4 amber amber  4096 Nov 20 15:48 .ros
-rw-rw-r--  1 amber amber    66 Dec  6  2023 .selected_editor
drwxrwxr-x  3 amber amber  4096 Nov 10 12:06 sin_wave
drwx------  2 amber amber  4096 Dec  6  2023 .ssh
-rw-r--r--  1 amber amber     0 Dec  6  2023 .sudo_as_admin_successful
-rw-rw-r--  1 amber amber   324 Jun 13  2024 test.py
-rw-------  1 amber amber   849 Dec 30  2023 .viminfo
-rw-rw-r--  1 amber amber    39 Jun 13  2024 watchlog.sh
-rw-rw-r--  1 amber amber    14 Dec  8  2023 watchTemp.sh
-rw-r--r--  1 root  root    180 Nov 18 16:54 .wget-hsts
-rw-rw-r--  1 amber amber   135 Jun 13  2024 zero.py

root@amber-master:~# ./b1.sh 
Master service is starting with status 2, wait a second please...
./b1.sh: line 49: /home/amber/ros2_ws/ros.out: No such file or directory
grep: /home/amber/ros2_ws/ros.out: No such file or directory
The Master is ready to serve....
B1 X-Hub is serving now......

root@amber-master:~# cat p.out 
python3: can't open file '/home/amber/amber_robot_studio_backend/manage.py': [Errno 2] No such file or directory
---------------------------------------------------------

**Comment by majdros** [comment]
<img width="1180" height="1094" alt="Image" src="https://github.com/user-attachments/assets/bc5176e6-0215-4102-919a-09a60ac76df2" />
