### ISSUE TITLE
AMBER B1 SDK & APIs: CAN bus protocol

### ISSUE THREAD

**Issue by bitengines** [AmberInside/Amber_AI_ROS2#14]
Hello,

Could be possible to have a description of the CAN protocol used with motors?. That would help  to control  the motors with other equiment as CAN interfaces are common in industrial equipment  like PLC's (Programable Logic Controller), or to develop aditional componets as grippers, tools or I/O to use with the robot.

Best regards

**Comment by AmberInside** [comment]
Currently it's still on development. Let backers know if there is any  beta or release version.  
A chance for CAN interface is when we launch our Joint series product.
