### ISSUE TITLE
What are the connector type used?

### ISSUE THREAD

**Issue by awtu2** [AmberInside/Amber_AI_ROS2#17]
I need to make a longer cable.  I believe the 2 wire (red and black)  is a power XT type connector. What is the 4 wire connector type?

**Comment by AmberInside** [comment]
4pin GH 1.25

**Comment by awtu2** [comment]
I couldn't find GH 1.25 on the web. I found JST GH 1.25 is that the same? I need female ends to make an extension. Can you suggest possible website to purchase
