### ISSUE TITLE
Connection Status always showed as "Disconnected"

### ISSUE THREAD

**Issue by billynew** [AmberInside/Amber_AI_ROS2#2]
I'm trying to run a basic demo with the web-based studio but it always showed "Connection Status: Disconnected".

Here is what I have gone through so far:

I created a bootable iso following this instruction: (https://github.com/AmberInside/Amber_AI_ROS2/wiki/AMBER-B1-Wiki-&-How). I was able to get into the Ubuntu system.

When trying to boot the robot, I did the following things in order:
1. plug the PSU (110V as I'm in US), the small green led on PSU is on
2. I released the e-stop of the robot. I can see each motor has a dimed red led on and motors are stiffed 
3. I wait a few sec and then plugin the host PC (the wooded box), wait for it to boot
4. I login the system and run the two scripts following this (https://github.com/AmberInside/Amber_AI_ROS2/wiki/Launch-AMBER-Studio,-web-based-controller-for-AMBER-B1)
5.  I then jump to the 127.0.0.1:85 
6. It showed disconnected and refresh doesn't help.
![IMG_6861](https://user-images.githubusercontent.com/1237408/153732774-f6144c91-cc6a-47fe-a5c4-7a544c425655.jpg)

Can you let me know if I'm doing anything wrong and how to fix this?

**Comment by billynew** [comment]
I've also tried the b1 program in the directory of '/home/amber/b1_demo/b1' and it works. The robot moves. So it has to be something with the web interface.

**Comment by AmberInside** [comment]
Did you click the the connection button  in the status bar,  behind the "disconnected" messaage?

**Comment by billynew** [comment]
Yes I tried that.

https://user-images.githubusercontent.com/1237408/153736076-4c8ca381-7377-4a8f-bda8-510e3706aa88.MOV

**Comment by AmberInside** [comment]
Try the steps below:
1,  Power off Master box;
2, Wait a minute after restarting Ubuntu, then power the **Master Box on** and **release the e-Stop**.  That would be helpful to make sure the hardware is ready to standby.
3, Run the 2 script and open firefox.
** Run /home/ros2_ws/start.sh  frist.

**Comment by billynew** [comment]
Thx it works this time. It seems that I have to go to the "Information" page, click the "Configuration" button, then click the "Connect" button on the top of the page.
