### ISSUE TITLE
Can we program the robot with Python or ROS2 SDK directly?

### ISSUE THREAD

**Issue by billynew** [AmberInside/Amber_AI_ROS2#3]
Hi, I'm wondering if we can control the robot beyond the web browser interface. 

I'm thinking to program the robot as a cam that can take photos of an object from a list of pre-defined positions. It seems that the web interface can only do joint-based control. Can you let me know if there is a way to program the robot?

**Comment by AmberInside** [comment]
Check the details by https://github.com/AmberInside/Amber_AI_ROS2/wiki/Protocol--for-AMBER-B1--SDK-&-APIs
