### ISSUE TITLE
What are the power requirements of the Amber B1? 

### ISSUE THREAD

**Issue by GHHofstetter** [AmberInside/Amber_AI_ROS2#5]
I believe my PSU is having some problems. I'd like to replace it with a new one (Don't worry I will buy).

I want to know the power requirements of the Amber B1 robot. You supplied us with a 48V supply, but on the Amber Wiki has this instruction. 
![image](https://user-images.githubusercontent.com/28851155/153941071-e765035f-57b9-4bfa-9d07-e142f82ea27f.png)

What is the Voltage needed for the arm (V) ? What is the Max current draw for the unit (A) ?

**Comment by AmberInside** [comment]
48V,.  The power is better beyond 400W,  or 600W if you are going to connected a gripper.
