### ISSUE TITLE
python api?

### ISSUE THREAD

**Issue by billynew** [AmberInside/Amber_AI_ROS2#6]
Hi there,

I'm wondering if the api.py under Is amber_robot_studio_backend/robot_api/public/python/ 
is the one that I should look into if I want to program the robot.

A quick test with the InitializeB1() function always return -1, no matter if the robot can be controlled from the web interface or not. Can you share any document on the python interface? Either the Chinese or English version should work. Thx!

**Comment by AmberInside** [comment]
Check protocol the details by https://github.com/AmberInside/Amber_AI_ROS2/wiki/Protocol--for-AMBER-B1--SDK-&-APIs

About Python coding, check the backend service code of web based GUI in the Master Controller,  that is written in Python with this protocol.

Or you can program B1 in any language you're good at.

**Comment by AmberInside** [comment]
Check the details by https://github.com/AmberInside/Amber_AI_ROS2/wiki/Protocol--for-AMBER-B1--SDK-&-APIs
