### ISSUE TITLE
Grey smoke from J7 when powered on

### ISSUE THREAD

**Issue by Allumnium** [AmberInside/Amber_AI_ROS2#9]
I have two Amber B1 robots and an identical setup for both. The cables were verified to be correct for both as well. When powering on one of the robots, it began to emit smoke from J7 after about 10 seconds and I quickly powered off with the E-stop.  I've attached a video of just before the smoke. It got to about 150 degrees F on the shell of the motor while it was smoking.

There was also a slight humming sound which was NOT present on the other robot (which mostly works). I did not identify the source of the humming sound so it could have come from either the power supply or the joint itself.

https://user-images.githubusercontent.com/55477274/154621396-e10f4faf-339f-445f-a4fa-59679e831b7c.mp4

What is the best way to diagnose this problem? I have disconnected the motor to see if I can open it and find the issue. (less relevant but while opening it a screw was missing). What would you recommend?

**Comment by AmberInside** [comment]
The temperature is not a problem.  please leave your mailing address and order details by email.  We'll help you to fix or replace it.

**Comment by Allumnium** [comment]
Thank you. I have sent an email to hello@amberobotics.com with address information

**Comment by AmberInside** [comment]
Drop you a mail around several days ago, but no response from you  yet. please  find such a mail that might be in the junk box and reply to us, so we can go to the next step to fix it.

**Comment by Allumnium** [comment]
I received the new motor and I have tested it. Everything works as expected now, thank you for your support. I will use the same shipping material to ship back the smoking motor
